name: Deploy Nebula

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  nebula_render:
    uses: ctrl-research/nebula-md/.github/workflows/deploy.yml@main
    with:
      vault_repo: j6nca/notes
      vault_directory: docs
      output_directory: output
      site_name: Jon's Blog 👨🏻‍💻
      ignored_dirs: "templates,scripts,.obsidian,assets,diagrams,drafts"
      graph_mode: nebula
